---
## Default Kibana configuration from kibana-docker.
## from https://github.com/elastic/kibana-docker/blob/master/build/kibana/config/kibana-full.yml
#
server.name: kibana
server.host: "0"
elasticsearch.url: http://es01:9200
#xpack.monitoring.collection.enabled: true

## X-Pack security credentials
#
elasticsearch.username: elastic
elasticsearch.password: secret

#
xpack.security.enabled: true