version: '2.2'

services:
  es01:
    container_name: es01
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    environment:
      - node.name=es01
      - discovery.zen.minimum_master_nodes=2
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD 
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    volumes: ['./elasticsearch01/data:/usr/share/elasticsearch/data']
    ports:
      - 9200:9200
    networks:
      - ek
    healthcheck:
      test: curl -s http://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5

  es02:
    container_name: es02
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    environment:
      - node.name=es02
      - discovery.zen.minimum_master_nodes=2
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - discovery.zen.ping.unicast.hosts=es01
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    networks:
      - ek
    volumes: ['./elasticsearch02/data:/usr/share/elasticsearch/data']

  wait_until_ready:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    command: /usr/bin/true
    depends_on: {"es01": {"condition": "service_healthy"}}
    
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:6.5.4
    environment:
      - ELASTICSEARCH_URL="http://es01:9200"
    ports:
      - 5601:5601
    networks:
      - ek
    depends_on:
      - es01  

networks:

  ek:
    driver: bridge